---
kind: pipeline
name: latest

trigger:
  event: push

steps:
- name: publish-full-latest
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "latest"
    dockerfile: Dockerfile
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish-alpine-latest
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "alpine"
    dockerfile: Dockerfile.alpine
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish-slim-latest
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "slim"
    dockerfile: Dockerfile.slim
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: versioned

trigger:
  event: tag

steps:
- name: publish-full
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "${DRONE_TAG}"
    dockerfile: Dockerfile
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish-alpine
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "${DRONE_TAG}-alpine"
    dockerfile: Dockerfile.alpine
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish-slim
  image: plugins/docker
  pull: if-not-exists
  depends_on:
    - clone
  settings:
    tags: "${DRONE_TAG}-slim"
    dockerfile: Dockerfile.slim
    repo: tonglil/auth-gcloud
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

...
